name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main  # Exécuter le workflow à chaque push sur la branche main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le code du dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Installer Doxygen
    - name: Install Doxygen
      run: sudo apt-get update && sudo apt-get install -y doxygen

    # Étape 3 : Générer la documentation
    - name: Generate Doxygen Documentation
      run: doxygen Doxyfile

    # Étape 4 : Déployer sur GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html